
function generatePassword(length = 8) {
  const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let password = "";

  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * charset.length);
    password += charset.charAt(randomIndex);
  }
  return password;
}

const defaultPassword = generatePassword();

const userConfirmation = window.prompt("Your generated password is:", defaultPassword);

 /*Math.random(): This function in JavaScript generates a pseudo-random
 floating-point number between 0 (inclusive) and 1 (exclusive). 
 So, Math.random() returns a random decimal number in the range [0, 1).

  charset.length: The charset variable represents the set of characters
   from which we want to generate the password. charset.length gives us
    the number of characters in the character set.
    
  Math.random() * charset.length: This multiplies the random decimal 
  number generated by Math.random() with the length of the character set. 
  This results in a random floating-point number in the range [0, charset.length).
    
   Math.floor(...): This function is used to round down the
    floating-point number to the nearest integer. This is important 
    because we want to use the result as an index for accessing elements 
    in an array or string (like charset). Rounding down ensures that 
    the index is within the valid range of indices.*/
